version: "3.8"
services:
  pg:
    build:
      context: ./postgres
      dockerfile: Dockerfile.pg
    volumes:
      - postgresqldata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    networks:
      - local

  afdd:
    build:
      context: .
    volumes:
      - ./logs:/afdd/logs
    env_file:
      - .env.dev
    depends_on:
      - pg
    networks:
      - local

networks:
  local:

volumes:
  postgresqldata:
