version: "3.8"
services:
  pg:
    build:
      context: ./extra/postgres
      dockerfile: Dockerfile.pg
    volumes:
      - postgresqldata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - local

  sample-data:
    build:
      context: .
      dockerfile: ./extra/sample_data/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@pg:5432/postgres
    depends_on:
      - pg
    networks:
      - local

  neo4j_with_plugins:
    build:
      context: .
      dockerfile: ./extra/neo4j/Dockerfile.neo4j
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - local

networks:
  local:

volumes:
  postgresqldata:
  neo4jdata:
  neo4jlogs:
