name: Dev Deploy
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/afdd-dev:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/afdd-dev:${{ github.sha }}

      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/afdd-dev:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: afdd-dev
          location: "east us"
          cpu: 1
          memory: 2
          env: 
            POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING_DEV }}
            NEO4J_URI: ${{ secrets.NEO4J_URI_DEV }}
            NEO4J_USER: ${{ secrets.NEO4J_USER_DEV }}
            NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD_DEV }}

